### ISSUE TITLE
Allow for non-integer dihedral values in library file?

### ISSUE THREAD

**Issue by hnisonoff** [donaldlab/OSPREY3#122] opened 2020-05-15 03:02 UTC
Is it possible to allow for rotamer libraries that specify decimal dihedral angles (e.g. 64.5) instead of just ints? I'm trying to play around with using smaller voxels + more rotamers. 

`rotamerValues[q][w] = Integer.parseInt(StringParsing.getToken(line,(w+1)));`

**Comment by cuchaz** [comment] 2020-05-15 14:11
Hi Hunter,

Yeah, that should be easily doable. I think all we need to do is change that `parseInt` to a `parseDouble`.

How familiar are you with Java? Want to send a PR?

**Comment by hnisonoff** [comment] 2020-05-15 17:54
Its been a long time but I think I can manage. I am having trouble building the python distribution. It seems that gradle does not recognize the conda environment I am using. 
I have `sphinx` installed:
```
(osprey_dev) hunternisonoff  13:51:17  ~/Box Sync/Berkeley/BioML/Covid19/moldyn/osprey_install/OSPREY3
> python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import guzzle_sphinx_theme
>>>
```

But then the build fails:
```
(osprey_dev) hunternisonoff  13:54:15  ~/Box Sync/Berkeley/BioML/Covid19/moldyn/osprey_install/OSPREY3
> ./gradlew assemble

> Configure project :
         Pythons:  [python3, python2, python]
        Python 2:  X
        Python 3:  X
  default Python:  Python 3 = python3

> Task :downloadTask UP-TO-DATE
> Task :processResources
> Task :appendBuildNumber
> Task :compileJava UP-TO-DATE
> Task :classes
> Task :jar UP-TO-DATE
> Task :startScripts UP-TO-DATE
> Task :distTar SKIPPED
> Task :distZip UP-TO-DATE
> Task :python2DistTar SKIPPED

> Task :makeDoc FAILED
Running Sphinx v2.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/hunternisonoff/anaconda3/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/hunternisonoff/anaconda3/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/hunternisonoff/Box Sync/Berkeley/BioML/Covid19/moldyn/osprey_install/OSPREY3/python/doc/conf.py", line 132, in <module>
    import guzzle_sphinx_theme
ModuleNotFoundError: No module named 'guzzle_sphinx_theme'


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':makeDoc'.
> Process 'command 'sphinx-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
7 actionable tasks: 3 executed, 4 up-to-date
```

**Comment by cuchaz** [comment] 2020-05-15 18:04
Ugh, it looks like the import should work from the logs you've posted. I'm not sure exactly what's going wrong here, but try disabling the doc generation as a simple workaround. You probably don't need to build the docs anyway.

I thought we had a flag to skip the docs generation, but I guess not. Just try editing the build script directly. Find these lines:
```kotlin
dependsOn(python2Wheel, makeDoc, python2InstallScripts, python2UninstallScripts)
```
and remove the `makeDoc` dependency:
```kotlin
dependsOn(python2Wheel, python2InstallScripts, python2UninstallScripts)
```

We can try to debug the conda environment later.

**Comment by hnisonoff** [comment] 2020-05-15 18:57
Ok that helped but now I have this error:
```
> Task :python3Wheel
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py:471: UserWarning: Normalizing '3.2-beta1' to '3.2b1'
  warnings.warn(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

> Task :python3Wheel FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':python3Wheel'.
> Process 'command 'python3'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by cuchaz** [comment] 2020-05-15 19:00
Looks like you're missing the `wheel` package. Try:
```shell
pip install wheel
```

FYI: here's all the prereqs:
```shell
pip install setuptools wheel sphinx==1.8 guzzle_sphinx_theme javalang
```

**Comment by hnisonoff** [comment] 2020-05-15 19:26
Yeah I think this is the same issue I was having with `guzzle_sphinx_theme`. These packages are installed.

I believe the issue is that my conda does not use `pip3`, but rather just uses `pip`. So when I build it is using my default system python. I don't think `pip3` is conda compatible... I'll edit the build script to just use `pip` for now

**Comment by hnisonoff** [comment] 2020-05-15 19:28
Edit: that did not work...

**Comment by hnisonoff** [comment] 2020-05-15 19:29
Oh I see the build system is not recognizing my conda:
`/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py:471: UserWarning: Normalizing '3.2-beta1' to '3.2b1'`

It is using the system-wide python

**Comment by cuchaz** [comment] 2020-05-15 20:02
Ugh, Python environments are so difficult to deal with. We're eventually going to abandon the pip command-line program entirely in favor of the `python -m pip` approach. You could try editing the scripts to do that? That might work better with your conda environment.

Btw, we've never run osprey inside a conda environment before, so that's probably why you're having all these problems. You're blazing a new trail! But if we get it working, osprey can support that extra environment, so others can benefit from your hard work too!

**Comment by hnisonoff** [comment] 2020-05-15 21:37
I was able to get it to work by hardcoding the python path:
```
		Python("/Users/hunternisonoff/anaconda3/envs/osprey_dev/bin/python3"),
		Python("/Users/hunternisonoff/anaconda3/envs/osprey_dev/bin/python2"),
		Python("/Users/hunternisonoff/anaconda3/envs/osprey_dev/bin/python")
```

I think the correct solution is to somehow have `gradlew` pass the correct python path from an environment variable into `build.gradle.kts`.

**Comment by cuchaz** [comment] 2020-05-15 21:45
Awesome, I'm glad you got it working. And that's a great suggestion too. I'll add it to the TODO list.

**Comment by gusennan** [comment] 2020-05-27 13:46
Do we need to test that this doesn't introduce any regressions?

**Comment by cuchaz** [comment] 2020-05-27 16:46
Assuming you're talking about the parseDouble vs parseInt thing, I think that's a pretty safe change.

**Comment by gusennan** [comment] 2020-05-27 16:49
Okay, closing.

**Closed by gusennan** 2020-05-27 16:49 UTC
Labels: enhancement
