### ISSUE TITLE
BBK* does not work with the sequence analyzer

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#107] opened 2019-12-09 03:12 UTC
It appears BBK* has a bug when the sequence analyzer is run on it.  Message from Florian G:

> And thank you for providing me the link to the script to write out ensembles. This works fine for me for the kstar method, but I always fail to adapt it to the bbkstar method. I just passed the configured bbkstar to the SequenceAnalyzer instead of the kstar.
'analyzer = osprey.SequenceAnalyzer(bbkstar)'
It tells me then:
'java.lang.NullPointerException
 	at
 edu.duke.cs.osprey.kstar.SequenceAnalyzer.analyze(SequenceAnalyzer.java:172)'

**Comment by gusennan** [comment] 2019-12-09 03:13
@jonathanjou I tagged you because I thought you might be interested in this report.

**Comment by cuchaz** [comment] 2019-12-10 15:43
I tried to debug this a bit... it looks like maybe a regression caused by some recent MARK**-related work?

It seems `BBKStar.ConfSpaceInfo` class was changed to use a `pfuncFactory` rather than the `confSearchFactoryXXX` members now. Yet, the `SequenceAnalyzer` still depends on the `confSearchFactoryMinimized` member, which is null. That's what causes the NPE as far as I can tell.

I'm not sure how to fix it though, but maybe JJ knows more?

**Comment by eternityslyre** [comment] 2019-12-10 18:58
Thanks for catching this, guys. I removed the requirement that BBKStar know
how the partition function is computed, since I was trying to compare
BBK*+A*-K* against BBK*+MARK*. I suggest two possible solutions:

1) Including code in SequenceAnalyzer or a separate class to create the
confSearchFactories given a BBKStar or KStar instance.
2) Modifying BBKStar and KStar to both have a "getConfSearchFactory"
function, and re-implementing that into BBKStar. This is in case someone
runs BBKStar+MARKStar, and then wants to analyze the sequence.

I'm leaning towards the former, since the dependency on BBKStar was just to
save time on recreating a confSearchFactory, and BBK* will eventually not
want to know about confSearchFactories at all. If that sounds good to you
guys I'll put it on the queue and try to get something by next Thursday.

**Comment by cuchaz** [comment] 2019-12-10 22:38
1) sounds good to me.

Another option might be to augment the `pfuncFactory` implementations to also spit out a `ConfSearch` on demand. That way, the `SequenceAnalyzer` can take the `pfuncFactory` from the BBK* instance (or K* instance) and ask it for a `ConfSearch`. Ideally, the generated `ConfSearch` uses the same methods for searching the conf space as the pfunc calculator. Or something similar... so the conformation generated by `SequenceAnalyzer` somewhat resembles the thing computed in the pfunc calculation.

**Comment by eternityslyre** [comment] 2020-02-05 00:18
I have pushed a change to SequenceAnalyzer and PartitionFunctionFactory so that SequenceAnalyzer usesPartitionFunctionFactory.makeConfSearchFactory to create the required object. Hopefully this fixes the bug!

For reference, MARK* doesn't use a ConfSeachFactory at all, and certainly doesn't enumerate conformations in order of lowest energy, so a SequenceAnalyzer running on MARK* results has to use something else. 

This bug should be fixed by the following two commits:
https://github.com/donaldlab/OSPREY3/commit/a99c1d452555232c14cee82ded7bbda9ec6db654
https://github.com/donaldlab/OSPREY3/commit/8300eabba49387ad9d78a3176a7569f7103c4b27

**Closed by eternityslyre** 2020-02-05 00:18 UTC
Labels: bug

**Comment by gusennan** [comment] 2020-02-05 14:13
@eternityslyre re: MARK* and conformation enumeration--good to know!
